export const ALARM_STATUSES = ['ACTIVE', 'ACKNOWLEDGED', 'RESOLVED']

export const ALARM_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

export const ALARM_TYPES = [
  'TEMPERATURE_HIGH',
  'TEMPERATURE_LOW',
  'HUMIDITY_HIGH',
  'HUMIDITY_LOW',
  'SMOKE_DETECTED',
  'WATER_LEAK',
  'SENSOR_OUT_OF_RANGE',
  'DEVICE_OFFLINE',
  'ENERGY_THRESHOLD',
]
