export const DEVICE_TYPES = [
  'HVAC',
  'LIGHT',
  'ENERGY_METER',
  'TEMPERATURE_SENSOR',
  'HUMIDITY_SENSOR',
  'SMOKE_SENSOR',
  'MOTION_SENSOR',
  'WATER_LEAK_SENSOR',
]

export const DEVICE_STATUSES = ['ONLINE', 'OFFLINE', 'MAINTENANCE', 'DISABLED']
