const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BUILDING_MANAGER: 'BUILDING_MANAGER',
  FACILITY_MANAGER: 'FACILITY_MANAGER',
  TECHNICIAN: 'TECHNICIAN',
  VIEWER: 'VIEWER',
};

const ALL_ROLES = Object.values(ROLES);

const PERMISSIONS = {
  'buildings:read': ALL_ROLES,
  'buildings:write': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER],
  'buildings:delete': [ROLES.SUPER_ADMIN],
  'structure:read': ALL_ROLES,
  'structure:write': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER],
  'devices:read': ALL_ROLES,
  'devices:write': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER, ROLES.FACILITY_MANAGER],
  'devices:update-status': [
    ROLES.SUPER_ADMIN,
    ROLES.BUILDING_MANAGER,
    ROLES.FACILITY_MANAGER,
    ROLES.TECHNICIAN,
  ],
  'devices:delete': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER, ROLES.FACILITY_MANAGER],
  'sensors:read': ALL_ROLES,
  'sensors:write': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER, ROLES.FACILITY_MANAGER],
  'readings:read': ALL_ROLES,
  'energy:read': ALL_ROLES,
  'reports:read': ALL_ROLES,
  'readings:write': [ROLES.SUPER_ADMIN, ROLES.FACILITY_MANAGER, ROLES.TECHNICIAN],
  'maintenance:read': ALL_ROLES,
  'maintenance:write': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER, ROLES.FACILITY_MANAGER],
  'maintenance:assign': [ROLES.SUPER_ADMIN, ROLES.BUILDING_MANAGER, ROLES.FACILITY_MANAGER],
  'maintenance:execute': [
    ROLES.SUPER_ADMIN,
    ROLES.BUILDING_MANAGER,
    ROLES.FACILITY_MANAGER,
    ROLES.TECHNICIAN,
  ],
  'alarms:read': ALL_ROLES,
  'alarms:acknowledge': [
    ROLES.SUPER_ADMIN,
    ROLES.BUILDING_MANAGER,
    ROLES.FACILITY_MANAGER,
    ROLES.TECHNICIAN,
  ],
  'alarms:resolve': [
    ROLES.SUPER_ADMIN,
    ROLES.BUILDING_MANAGER,
    ROLES.FACILITY_MANAGER,
    ROLES.TECHNICIAN,
  ],
  'users:manage': [ROLES.SUPER_ADMIN],
};

module.exports = { ROLES, ALL_ROLES, PERMISSIONS };
